[package]
name = "simple_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2 = "0.0.0"
halo2_proofs = "0.3.0"
group = "0.13.0"

